"""empty message

Revision ID: 2563479dce65
Revises: 
Create Date: 2020-09-28 21:13:56.496583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2563479dce65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blogs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_pictures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pitch_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['blogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('profile_pictures')
    op.drop_table('blogs')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
