"""empty message

Revision ID: c18d174be3b5
Revises: 2563479dce65
Create Date: 2020-09-28 21:17:54.933659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18d174be3b5'
down_revision = '2563479dce65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletters')
    # ### end Alembic commands ###
